export const REGISTER_USER = "REGISTER_USER";
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_PROFILE = "GET_PROFILE ";

//Email
export const SEND_EMAIL_MESSAGE = "SEND_EMAIL_MESSAGE";
export const MESSAGE_MAIL_LOADING = "MESSAGE_MAIL_LOADING ";
export const MESSAGE_MAIL_SENT = "MESSAGE_MAIL_SENT";
